# Generated by Django 4.2.5 on 2023-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(default="Unknown author", max_length=255)),
                ("title", models.CharField(default="Unknown title", max_length=255)),
                ("url", models.URLField(default="Unknown URL")),
            ],
        ),
    ]
