# Generated by Django 4.2.5 on 2023-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_date",
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(default="Unknown Address", max_length=200),
        ),
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.CharField(default="Unknown Date", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="link",
            field=models.URLField(default="Unknown Link"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(default="Unknown Title", max_length=200),
        ),
    ]
