# Generated by Django 4.2.5 on 2023-10-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(default="Description not available", max_length=300),
        ),
    ]
